FROM node:21-alpine3.18 AS builder

WORKDIR /usr/local/app

COPY /frontend .

RUN npm install

RUN npm run build:docker

FROM nginx:1.21.3-alpine

COPY /frontend/.nginx/nginx.conf /etc/nginx/conf.d/nginx.conf
COPY --from=builder /usr/local/app/dist/adelium /usr/share/nginx/html

EXPOSE 80