services:
  #######################################################################################################
  # databases
  #######################################################################################################

  ##########################################
  # data-auth:
  ##########################################
  data-auth:
    container_name: data-auth
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - data-auth-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: adel_auth

  ##########################################
  # data-quiz:
  ##########################################
  data-quiz:
    container_name: data-quiz
    image: mysql:8.3.0
    ports:
      - "3308:3306"

    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - data-quiz-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: adel_quiz

  ##########################################
  # data-media:
  ##########################################
  data-media:
    container_name: data-media
    image: mysql:8.3.0
    ports:
      - "3309:3306"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - data-media-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: adel_media

  #######################################################################################################
  # backend
  #######################################################################################################

  ##########################################
  # config-service
  ##########################################
  config-service:
    container_name: config-service
    image: gcr.io/silicon-will-412308/config-service:v1
    ports:
      - "8888:8888"
    healthcheck:
      test: wget -qO- http://localhost:8888/actuator/health || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: docker
  ##########################################
  # discovery-service
  ##########################################
  discovery-service:
    container_name: discovery-service
    image: gcr.io/silicon-will-412308/discovery-service:v1
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: wget -qO- http://localhost:8761/actuator/health || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_PASSWORD: password
      CONFIG_SERVICE_USERNAME: user

  ##########################################
  # gateway-service
  ##########################################
  gateway-service:
    container_name: gateway-service
    image: gcr.io/silicon-will-412308/gateway-service:v1
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: wget -qO- http://localhost:8080/actuator/health || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_PASSWORD: password
      CONFIG_SERVICE_USERNAME: user

  ##########################################
  # auth-service
  ##########################################
  auth-service:
    container_name: auth-service
    image: gcr.io/silicon-will-412308/auth-service:v1
    ports:
      - "8081:8081"
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      data-auth:
        condition: service_started
    healthcheck:
      test: wget -qO- http://localhost:8081/actuator/health || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_PASSWORD: password
      CONFIG_SERVICE_USERNAME: user


  ##########################################
  # quiz-service
  ##########################################
  quiz-service:
    container_name: quiz-service
    image: gcr.io/silicon-will-412308/quiz-service:v1
    ports:
      - "8082:8082"
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      data-quiz:
        condition: service_started
    healthcheck:
      test: wget -qO- http://localhost:8082/actuator/health || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_PASSWORD: password
      CONFIG_SERVICE_USERNAME: user


  ##########################################
  # media-service
  ##########################################
  media-service:
    container_name: media-service
    image: gcr.io/silicon-will-412308/media-service:v1
    ports:
      - "8083:8083"
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      data-media:
        condition: service_started
    healthcheck:
      test: wget -qO- http://localhost:8083/actuator/health || exit 1
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_PASSWORD: password
      CONFIG_SERVICE_USERNAME: user


  #######################################################################################################
  # frontend
  #######################################################################################################

  ##########################################
  # frontend-angular
  ##########################################
  # frontend-angular:
  #   container_name: frontend-angular
  #   image: gcr.io/silicon-will-412308/front-service:v1
  #   ports:
  #     - "443:443"
  #   environment:
  #     PRODUCTION: true

#######################################################################################################
# volumes
#######################################################################################################
volumes:
  data-auth-vol:
  data-quiz-vol:
  data-media-vol:
