apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: config-service
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/adelium-default: "true"
        io.kompose.service: config-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: gcr.io/silicon-will-412308/config-service:v2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 25
            timeoutSeconds: 10
          name: config-service
          ports:
            - containerPort: 8888
              # hostPort: 8888
              protocol: TCP
          resources: 
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 500m
              ephemeral-storage: 500Mi
              memory: 512Mi
      restartPolicy: Always
status: {}
