apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data-auth-vol
  name: data-auth-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
status: {}
