apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: data-auth
  name: data-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/adelium-default: "true"
        io.kompose.service: data-auth
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: adel_auth
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql:8.3.0
          livenessProbe:
            exec:
              command:
                - mysqladmin ping -h localhost
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 25
            timeoutSeconds: 10
          name: data-auth
          ports:
            - containerPort: 3306
              # hostPort: 3307
              protocol: TCP
          resources: 
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 500m
              ephemeral-storage: 500Mi
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-auth-vol
      restartPolicy: Always
      volumes:
        - name: data-auth-vol
          persistentVolumeClaim:
            claimName: data-auth-vol
status: {}
