apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: discovery-service
status:
  loadBalancer: {}
