spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_USERNAME:user}:${CONFIG_SERVICE_PASSWORD:password}@config-service:8888
  application:
    name: discovery-service
server:
  port: 8761