server:
  port: 8082
  ssl:
    key-alias: quiz-service
    key-store: classpath:quiz-service.jks
    key-store-type: JKS
    key-store-password: password
    trust-store: classpath:truststore.jks
    trust-store-password: password
    trust-store-type: JKS
    enabled: true

spring:
  config:
    import: optional:configserver:https://${CONFIG_SERVICE_USERNAME:user}:${CONFIG_SERVICE_PASSWORD:password}@config-service:8888
  application:
    name: quiz-service