apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Hakim\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.prod.yml -o kubernetes-files/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/adelium-default: "true"
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
            - name: CONFIG_SERVICE_USERNAME
              value: user
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: gcr.io/silicon-will-412308/auth-service:v2
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - sleep 1000
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 25
            timeoutSeconds: 10
          name: auth-service
          ports:
            - containerPort: 8081
              # hostPort: 8081
              protocol: TCP
          resources: 
            limits:
              cpu: 2000m
              ephemeral-storage: 2Gi
              memory: 2Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 1Gi
              memory: 1Gi
      restartPolicy: Always
status: {}