server:
  port: 8888

spring:
  security:
    user:
      name: ${CONFIG_SERVICE_USERNAME:user}
      password: ${CONFIG_SERVICE_PASSWORD:password}
  application:
    name: config-service
  config:
    import: application-secret.yaml
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: "https://github.com/saoudi-h/adelium-config-cloud-github"
          username:
          password:
management:
  endpoints:
    web:
      exposure:
        include: '*'