server:
  port: 8888

spring:
  config:
    name: config-service
    import: application-secret.yaml
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: "https://github.com/saoudi-h/adelium-config-cloud-github"
          username:
          password:
management:
  endpoints:
    web:
      exposure:
        include: '*'