#!/bin/sh

stagedFiles=$(git diff --staged --name-only)
back=false
front=false

for file in $stagedFiles; do
  if $back && $front && $docs; then
    break
  fi
  if ! $front && [[ $file == "frontend/"* ]]; then
    front=true
  fi
  if ! $back && [[ $file == "backend/"* ]]; then
    back=true
  fi
done

# S'ils y a des fichiers frontend/
if $front; then
  echo "Front-end commit détecté. Exécution de npx lint-staged pour le front-end..."
  (
    cd frontend || exit
    npx lint-staged
  )
fi

# S'ils y a des fichiers backend/
if $back; then
  echo "Running spotlessApply. Formatting code..."
  (
    cd backend || exit
    ./gradlew spotlessApply
  )

  # Part 3
  for file in $stagedFiles; do
    if test -f "$file"; then
      git add "$file"
    fi
  done
fi

# Validation
exit 0
